# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'

use_modular_headers!
prepare_react_native_project!

require_relative '../node_modules/react-native-permissions/scripts/setup'

setup_permissions([
  'Camera',
  'LocationWhenInUse',
  'Microphone',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end



target 'Smpl' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    envfiles = {
      'Debug' => '$(PODS_ROOT)/../../.env.development',
      'Release' => '$(PODS_ROOT)/../../.env.production',
    }

    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-config'
        target.build_configurations.each do |config|
          config.build_settings['ENVFILE'] = envfiles[config.name]
        end
      end
    end
  end
end
