import React from 'react';
import {useColorScheme} from 'react-native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import ShowImage from '../screens/imageMap/showImage'; import ShowMap from '../screens/imageMap/showMap';
import Attendancelist from '../screens/attandance/attendanceList'; import LeaveList from '../screens/leave/leaveList'; import AddLeave from '../screens/leave/addLeave';
import AdminAttendancelist from '../screens/attandance/admin/adminAttendance'; import ProjectList from '../screens/profile/project/projectList'; import ModuleList from '../screens/profile/project/module/moduleList'; import AddModule from '../screens/profile/project/module/addModule';
import NotificationScreen from '../screens/notification/notificationScreen'; import TabNavigator from './tabNavigator'; import HolidayList from '../screens/profile/holiday/holidayList'; import {AppStackParamList} from './navigationTypes'; import AdminTabNavigator from './adminTabNavigator'; import {useAuth} from '../context/authContext';
import AttendanceFilter from '../screens/attandance/attendanceFilter'; import performanceReport from '../screens/home/performanceReport'; import Salary from '../screens/profile/salary/salary'; import projectReminder from '../screens/profile/projectRemain/projectReminder'; import addProjectReminder from '../screens/profile/projectRemain/addProjectReminder'; import AddProjectRemainingScreen from '../screens/profile/projectRemain/addProjectRemainingScreen'; import ProjectRemainingScreen from '../screens/profile/projectRemain/projectRemainingScreen'; import ServiceVisitList from '../screens/serviceVisit/serviceVisitList'; import AddServiceVisit from '../screens/serviceVisit/addServiceVisit'; import CalculateSalary from '../screens/accounts/calculateSalary';
const Stack=createNativeStackNavigator<AppStackParamList>();
export default function AppStack({initialRoute}:{initialRoute:keyof AppStackParamList}){const {userInfo}=useAuth();const dark=useColorScheme()==='dark';const bg=dark?'#08121E':'#F4F7FB';const surface=dark?'#102236':'#FFFFFF';const text=dark?'#F4F8FC':'#0B1728';
 const detail=(title:string)=>({title,headerShown:true,headerBackTitle:'',headerBackButtonDisplayMode:'minimal' as const,headerStyle:{backgroundColor:surface},headerTintColor:text,headerTitleStyle:{color:text,fontSize:17,fontWeight:'800' as const},headerShadowVisible:false});
 return <Stack.Navigator initialRouteName={userInfo?.role==='Owner'||userInfo?.role==='Admin'?'AdminTabNavigator':'TabNavigator'} screenOptions={{contentStyle:{backgroundColor:bg},headerShown:true,headerBackTitle:'',headerBackButtonDisplayMode:'minimal'}}>
 {(userInfo?.role==='Owner'||userInfo?.role==='Admin')?<Stack.Screen name="AdminTabNavigator" component={AdminTabNavigator} options={{headerShown:false}}/>:<Stack.Screen name="TabNavigator" component={TabNavigator} options={{headerShown:false}}/>}
 <Stack.Screen name="showImage" component={ShowImage} options={{headerShown:false}}/><Stack.Screen name="showMap" component={ShowMap} options={{...detail('Attendance Location')}}/>
 <Stack.Screen name="Attendancelist" component={Attendancelist} options={detail('Attendance List')}/><Stack.Screen name="AttendanceFilter" component={AttendanceFilter} options={detail('Attendance Calendar')}/><Stack.Screen name="LeaveList" component={LeaveList} options={detail('Leave Requests')}/><Stack.Screen name="AddLeave" component={AddLeave} options={detail('New Leave Request')}/><Stack.Screen name="AdminAttendancelist" component={AdminAttendancelist} options={detail('Attendance List')}/><Stack.Screen name="NotificationScreen" component={NotificationScreen} options={detail('Notifications')}/><Stack.Screen name="Project" component={ProjectList} options={detail('Projects')}/><Stack.Screen name="ModuleList" component={ModuleList} options={detail('Module List')}/><Stack.Screen name="AddModule" component={AddModule} options={detail('Add Module')}/><Stack.Screen name="HolidayList" component={HolidayList} options={detail('Holiday List')}/><Stack.Screen name="PerformanceReport" component={performanceReport} options={detail('Performance')}/><Stack.Screen name="Salary" component={Salary} options={detail('Salary')}/><Stack.Screen name="ProjectReminder" component={projectReminder} options={detail('Reminders')}/><Stack.Screen name="AddProjectReminder" component={addProjectReminder} options={detail('Add Reminder')}/><Stack.Screen name="AddProjectRemainingScreen" component={AddProjectRemainingScreen} options={detail('Add Project Remaining')}/><Stack.Screen name="ProjectRemainingScreen" component={ProjectRemainingScreen} options={detail('Project Remaining')}/><Stack.Screen name="ServiceVisitList" component={ServiceVisitList} options={detail('Service Visits')}/><Stack.Screen name="AddServiceVisit" component={AddServiceVisit} options={detail('New Service Visit')}/><Stack.Screen name="CalculateSalary" component={CalculateSalary} options={detail('Salary Calculation')}/>
 </Stack.Navigator>
}
